Remove quote from 'draco-code-comment-width, so that set-fill-column works.
Without this, emacs 24.3 reports

error: set-fill-column requires an explicit argument